export type { FormatHandler } from './format-handler';
export type { FormatContext, TableEmitOptions } from './format-context';
export { FormatContextImpl, createReferenceRegistry, registerReference, getRegistryEntries } from './format-context';
export { compile } from './compile';
export { loadTheme, listThemes } from './theme-loader';
export type { ThemeDefinition } from './theme-loader';
export { resolveConfig } from './config-resolver';
export { formatNumber, toAlpha, toRoman } from './numbering';
export { createImageResolver } from './image';
export type { ResolvedImage } from './image';
export { inlineToElements, inlinePlainText } from './inline';
export type { InlineContext, InlineLinkMode, InlineLinkOptions } from './inline';
